services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=z9StDrGI2b7tXah5KExx/+eZ5bj3cmHv/6+u3t9G+wc=%
      - NACOS_AUTH_IDENTITY_KEY=b415ae829b2b6026be272bea6c7afe40
      - NACOS_AUTH_IDENTITY_VALUE=7ccb516f2be0bce638a2f2a208fd09acf66b65cf03b84ddbc7f0d1a72ee20fec
