// Code generated by Wire. DO NOT EDIT.


package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/spigcoder/sp_code/system/ioc"
	"github.com/spigcoder/sp_code/system/repository"
	"github.com/spigcoder/sp_code/system/repository/dao"
	"github.com/spigcoder/sp_code/system/service"
	"github.com/spigcoder/sp_code/system/web"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	db := ioc.InitDB()
	sysUserDao := dao.NewSysUserDaoImpl(db)
	sysUserRepository := repository.NewSysUserRepositoryImpl(sysUserDao)
	sysUserService := service.NewSysUserServiceImpl(sysUserRepository)
	sysUserHandler := web.NewSysUserHandler(sysUserService)
	engine := ioc.InitWeb(sysUserHandler)
	return engine
}

// wire.go:

// 定义 Provider Set
var WebServerSet = wire.NewSet(ioc.InitDB, dao.NewSysUserDaoImpl, repository.NewSysUserRepositoryImpl, service.NewSysUserServiceImpl, web.NewSysUserHandler, ioc.InitWeb)
